<?php

namespace mtBundle\Repository;

/**
 * FichefraisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FichefraisRepository extends \Doctrine\ORM\EntityRepository
{
}
