<?php

namespace mtBundle\Repository;

/**
 * VisiteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisiteurRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByLoginAndMdp($login, $mdp) {
// Retourne le visiteur dont le login et le mdp sont donnés en paramètre
$queryBuilder = $this->createQueryBuilder('v') ;
// Utilisation de requêtes paramétrées
$queryBuilder->where('v.login = :login')
->setParameter('login',$login)
->andWhere('v.mdp = :mdp')
->setParameter('mdp',$mdp) ;
// équivalent à :
// $queryBuilder->where('v.login = :login')
// ->andWhere('v.mdp = :mdp')
// ->setParameters(array('login'=>$login, 'mdp'=>$mdp)) ;
// Retourner le résultat : ligne en cas de succès, null sinon
return $queryBuilder->getQuery() -> getResult() ;
}
}
